import { select, confirm } from '@inquirer/prompts';
import { execSync } from 'child_process';
import { readFileSync, existsSync, writeFileSync } from 'fs';
import { dirname } from 'path';
import dotenv from 'dotenv';
import { migrateToPhrase } from './migrate';
import { getWebKeyValue } from './getWebKeyValue';

// Load environment variables from .env file
dotenv.config();

interface ProjectType {
  name: string;
  value: 'trade' | 'pages';
}

async function main() {
  console.log('🚀 Starting i18n Migration Process\n');
  const existingKeys: Set<string> = new Set();

  // Step 1: Interactive selection between Trade and Pages
  console.log('Step 1: Select project type');
  const projectType = await select({
    message: 'Select project type:',
    choices: [
      { name: 'Trade', value: 'trade' },
      { name: 'Pages', value: 'pages' }
    ],
    default: 'pages'
  }) as 'trade' | 'pages';

  console.log(`\n📋 Selected: ${projectType === 'trade' ? 'Trade' : 'Pages'}\n`);

  // Step 2: Run getWebKeyValue.ts
  console.log('Step 2: Running getWebKeyValue.ts...');
  const { webKeyValue } = getWebKeyValue() ?? {}



  // console.log(webKeyValue)
  if (!webKeyValue) {
    throw new Error('getWebKeyValue.ts failed to return webKeyValue');
  }


  // return Promise.resolve(void 0)

  // try {
  //   // execSync('npx ts-node getWebKeyValue.ts', { stdio: 'inherit' });

  //   const { webKeyValue } = getWebKeyValue() ?? {}
  //   // if (!translations) {
  //   //   throw new Error('getWebKeyValue.ts failed to return translations');
  //   // }
  //   console.log('\n✅ getWebKeyValue.ts completed successfully!\n');
  // } catch (error) {
  //   console.error('\n❌ Error running getWebKeyValue.ts:', error instanceof Error ? error.message : String(error));
  //   process.exit(1);
  // }



  // Step 4: Check if keys already exist in source JSON
  console.log('Step 4: Checking for existing keys in source JSON...');
  try {
    // Determine source JSON path based on project type
    let sourceJsonPath: string;
    if (projectType === 'trade') {
      sourceJsonPath = process.env.TRADE_PROJECT_JSON!
      if (!sourceJsonPath) {
        throw new Error('TRADE_PROJECT_JSON not found in .env file');
      }
    } else {
      sourceJsonPath = process.env.PAGES_PROJECT_JSON!
      if (!sourceJsonPath) {
        throw new Error('PAGES_PROJECT_JSON not found in .env file');
      }
    }

    // Validate source JSON file exists
    if (!existsSync(sourceJsonPath)) {
      throw new Error(`Source JSON file not found: ${sourceJsonPath}`);
    }

    // Update git repository to latest main branch if sourceJsonPath is in a git repo
    try {
      const sourceDir = dirname(sourceJsonPath);
      console.log(`\n🔄 Checking if ${sourceDir} is a git repository...`);
      
      // Check if it's a git repository
      execSync('git rev-parse --is-inside-work-tree', { cwd: sourceDir, stdio: 'ignore' });
      
      console.log(`📂 ${sourceDir} is a git repository. Updating to latest main branch...`);
      
      // Fetch latest changes
      execSync('git fetch origin', { cwd: sourceDir, stdio: 'inherit' });
      
      // Checkout main branch
      execSync('git checkout main', { cwd: sourceDir, stdio: 'inherit' });
      
      // Pull latest changes
      execSync('git pull origin main', { cwd: sourceDir, stdio: 'inherit' });
      
      console.log(`✅ Successfully updated to latest main branch`);
    } catch (error) {
      // If not a git repository, just continue
      console.log(`📁 Not a git repository, skipping update...`);
    }

    // Read and parse source JSON
    const sourceJsonContent = readFileSync(sourceJsonPath, 'utf-8');
    const sourceJson = JSON.parse(sourceJsonContent);

    // reset valuesByLocale.ts with export const valuesByLocale = {}
    // writeFileSync('./valuesByLocale.ts', 'export const valuesByLocale = {}');
    

    // Dynamically import valuesByLocale (generated by getWebKeyValue.ts)
    console.log('\n🔄 Importing valuesByLocale...');
    // const { valuesByLocale } = await import('./valuesByLocale');

    // Collect all unique keys from valuesByLocale
    const keysToMigrate = new Map<string, string>();
    Object.entries(webKeyValue).forEach(([locale, localeValues]) => {
      if (locale !== 'zh-CN') return
      Object.entries(localeValues).forEach(([key, value]) => {
        keysToMigrate.set(key, value);
      });
    });

    // Check for existing keys
    keysToMigrate.forEach((value, key) => {
      if (sourceJson.hasOwnProperty(key)) {
        if (sourceJson[key] !== value) {
          console.log(`  - ${key} (${sourceJson[key]}) !== ${value}`);
          // Key exists but value differs
          existingKeys.add(key);
        }
      }
    });

    // Handle existing keys
    if (existingKeys.size > 0) {
      console.error('\n❌ Error: The following keys already exist in the source JSON:');
      // existingKeys.forEach(key => console.error(`  - ${key.key} (${key.value})`));
      console.error('\nPlease remove these keys from the migration or update the source JSON first.');
      process.exit(1);
    }

    console.log('\n✅ No existing keys found! Proceeding with migration...\n');
  } catch (error) {
    console.error('\n❌ Error during key validation:', error instanceof Error ? error.message : String(error));
    process.exit(1);
  }


  // Step 3: Confirm proceeding with migration
  console.log('Step 3: Confirm migration');
  const isConfirmed = await confirm({
    message: 'getWebKeyValue.ts has completed successfully. Do you want to proceed with the migration?',
    default: true
  });

  if (!isConfirmed) {
    console.log('\n🚫 Migration cancelled by user');
    process.exit(0);
  }

  console.log('\n✅ Proceeding with migration...\n');

  // Step 5: Call migrateToPhrase with the appropriate project ID
  console.log('Step 5: Migrating translations to Phrase...');
  try {
    let projectId: string;

    if (projectType === 'trade') {
      projectId = process.env.TRADE_PROJECT_ID!
      if (!projectId) {
        throw new Error('TRADE_PROJECT_ID not found in .env file');
      }
    } else {
      projectId = process.env.PAGES_PROJECT_ID!
      if (!projectId) {
        throw new Error('PAGES_PROJECT_ID not found in .env file');
      }
    }

    console.log(`\n📋 Using project ID: ${projectId}`);
    console.log('📋 Migrating translations...\n');

    await migrateToPhrase(projectId, webKeyValue, existingKeys);

    console.log('\n🎉 All steps completed successfully!');
  } catch (error) {
    console.error('\n❌ Error during migration:', error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}

// Run the main function
main().catch(console.error);
