import { select } from '@inquirer/prompts';
import { execSync } from 'child_process';
import { readFileSync, existsSync } from 'fs';
import dotenv from 'dotenv';
import { migrateToPhrase } from './migrate';

// Load environment variables from .env file
dotenv.config();

interface ProjectType {
  name: string;
  value: 'trade' | 'pages';
}

async function main(): Promise<void> {
  console.log('🚀 Starting i18n Migration Process\n');

  // Step 1: Interactive selection between Trade and Pages
  console.log('Step 1: Select project type');
  const projectType = await select({
    message: 'Select project type:',
    choices: [
      { name: 'Trade', value: 'trade' },
      { name: 'Pages', value: 'pages' }
    ],
    default: 'pages'
  }) as 'trade' | 'pages';

  console.log(`\n📋 Selected: ${projectType === 'trade' ? 'Trade' : 'Pages'}\n`);

  // Step 2: Run getWebKeyValue.ts
  console.log('Step 2: Running getWebKeyValue.ts...');
  try {
    execSync('npx ts-node getWebKeyValue.ts', { stdio: 'inherit' });
    console.log('\n✅ getWebKeyValue.ts completed successfully!\n');
  } catch (error) {
    console.error('\n❌ Error running getWebKeyValue.ts:', error instanceof Error ? error.message : String(error));
    process.exit(1);
  }

  // Step 3: Check if keys already exist in source JSON
  console.log('Step 3: Checking for existing keys in source JSON...');
  try {
    // Determine source JSON path based on project type
    let sourceJsonPath: string;
    if (projectType === 'trade') {
      sourceJsonPath = process.env.TRADE_PROJECT_JSON!
      if (!sourceJsonPath) {
        throw new Error('TRADE_PROJECT_JSON not found in .env file');
      }
    } else {
      sourceJsonPath = process.env.PAGES_PROJECT_JSON!
      if (!sourceJsonPath) {
        throw new Error('PAGES_PROJECT_JSON not found in .env file');
      }
    }

    // Validate source JSON file exists
    if (!existsSync(sourceJsonPath)) {
      throw new Error(`Source JSON file not found: ${sourceJsonPath}`);
    }

    // Read and parse source JSON
    const sourceJsonContent = readFileSync(sourceJsonPath, 'utf-8');
    const sourceJson = JSON.parse(sourceJsonContent);

    // Dynamically import valuesByLocale (generated by getWebKeyValue.ts)
    const { valuesByLocale } = await import('./valuesByLocale');

    // Collect all unique keys from valuesByLocale
    const keysToMigrate = new Set<string>();
    Object.entries(valuesByLocale).forEach(([locale, localeValues]) => {
      // @ts-ignore
      Object.entries(localeValues).forEach(([key]) => {
        keysToMigrate.add(key);
      });
    });

    // Check for existing keys
    const existingKeys: string[] = [];
    keysToMigrate.forEach(key => {
      if (sourceJson.hasOwnProperty(key)) {
        existingKeys.push(key);
      }
    });

    // Handle existing keys
    if (existingKeys.length > 0) {
      console.error('\n❌ Error: The following keys already exist in the source JSON:');
      existingKeys.forEach(key => console.error(`  - ${key}`));
      console.error('\nPlease remove these keys from the migration or update the source JSON first.');
      process.exit(1);
    }

    console.log('\n✅ No existing keys found! Proceeding with migration...\n');
  } catch (error) {
    console.error('\n❌ Error during key validation:', error instanceof Error ? error.message : String(error));
    process.exit(1);
  }

  // Step 4: Call migrateToPhrase with the appropriate project ID
  console.log('Step 4: Migrating translations to Phrase...');
  try {
    let projectId: string;

    if (projectType === 'trade') {
      projectId = process.env.TRADE_PROJECT_ID!
      if (!projectId) {
        throw new Error('TRADE_PROJECT_ID not found in .env file');
      }
    } else {
      projectId = process.env.PAGES_PROJECT_ID!
      if (!projectId) {
        throw new Error('PAGES_PROJECT_ID not found in .env file');
      }
    }

    console.log(`\n📋 Using project ID: ${projectId}`);
    console.log('📋 Migrating translations...\n');

    await migrateToPhrase(projectId);

    console.log('\n🎉 All steps completed successfully!');
  } catch (error) {
    console.error('\n❌ Error during migration:', error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}

// Run the main function
main().catch(console.error);
